plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/eemm/CoWork/InvenioWeb"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "http://inveniotech.org/*"
to = "https://inveniotech.org/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "http://www.inveniotech.org/*"
to = "https://inveniotech.org/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://www.inveniotech.org/*"
to = "https://inveniotech.org/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]